resources:
- statefulset.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: roto-redis-env
  literals:
    - REDIS_PASSWORD=e9HuasAac9R8ZADJdxITpq
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=roto-redis

