resources:
- statefulset.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: roto-kafka-env
  literals:
    - KAFKA_LISTENERS=PLAINTEXT://localhost:29092,CONTROLLER://localhost:29093,PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://roto-kafka:29092,PLAINTEXT_HOST://roto-kafka:9092,PLAINTEXT_INTERNAL://roto-kafka:9093
    - KAFKA_LOG_DIRS=/var/lib/kafka/data
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=roto-kafka

