---
apiVersion: v1
kind: Service
metadata:
  name: roto-kafka
spec:
  type: ClusterIP
  selector:
    app: roto-kafka
  ports:
  - name: tcp
    port: 9092
    targetPort: 9092
  - name: internal
    port: 9093
    targetPort: 9093
