apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - l2-policy.yaml
  - ip-pool.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.18.4 # renovate: github-releases=cilium/cilium
    releaseName: "cilium"
    includeCRDs: true
    namespace: kube-system
    valuesFile: values.yaml
