resources:
- deployment.yaml
- service.yaml
- api.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: rotoapi-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=rotoapi
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=https://+:5555
    - HTTPS_PORT=555
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
    - ASPNETCORE_Kestrel__Certificates__Default__Password=123456

secretGenerator:
- name: rotoapi-secrets
  envs:
  - .rotoapi.secrets
