resources:
- deployment.yaml
- service.yaml
- ui.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: rotoui-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - services__rotoapi__http__0=http://rotoapi:5555
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=rotoui
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=https://+:5140
    - HTTPS_PORT=5141
    - HTTPS_PORTS=5140
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
    - ASPNETCORE_Kestrel__Certificates__Default__Password=123456

secretGenerator:
- name: rotoui-secrets
  envs:
  - .rotoui.secrets
